name: Linting

on: push

jobs:
  flake8:
    runs-on: self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: setup requirements
        run: pip install flake8

      - name: run flake8
        run: flake8 --max-line-length=120 --ignore=E203,W503,E711 src/
